### ISSUE TITLE
Transaction Support

### ISSUE THREAD

**Issue by teburd** [extend/bank#3]
We talked about this before but I'm tired of emysql and epgsql oddities. Its time to make bank awesome and step one for me is transaction support.

The interface I want for batch and transaction is basically given an in the following example.

``` erlang
bank:transaction(my_pool_name,
    fun(C) -> 
        {rows, Stuff} = bank:query(C, "select * from awesome"),
        Stuff0 = process(Stuff),
        {ok, N, M} = bank:query(C, "insert into stuff", Stuff)
    end
),
```

The reason I want to reuse the bank module interface should be pretty clear I hope, its so that I can write reusable little functions like

set_latest(C, DateTime) ->
       bank:query(C, "update latest ....", [DateTime]).

Without having to know ahead of time set_latest will always or not always be in a transaction/batch function, what the current state of the sql connection is, what driver the sql connection is using, etc etc.

So now that the desired interface is hopefully clear, and the reasons clear, there's two implementation options for the purpose of holding the state of the calling context.
1. Seperate Connection Process with crafted tuple
2. Process Dictionary

Using a seperate connection process bank:query might look like

``` erlang
query({'$BANK_CONN', Module, Pid}, Query) ->
     Module(Pid, Query);
query(Ref, Query) ->
    {ok, Pid} = bank_server:get_worker(Ref),
     bank_worker:query(Pid, Query).
```

The crafted tuple would be created by bank_worker:transaction or bank_worker:batch and be given to the provided fun/1.

Using a process dict for storing connection state bank:query might look like

``` erlang
query(Ref, Query) ->
        case get('$BANK_BATCH') of
               {Module, State} ->
                     {Result, State0} = Module:query(Query, State),
                      set('$BANK_BATCH, State0)
                undefined ->
                      {ok, Pid} = bank_server:get_worker(Ref),
                       bank_worker:query(Pid, Query)
        end.
```

Here the dict is the bank_worker process dict (totally fine) and basically at the very end of the transaction
the connection state would be retrieved and removed from the dict. bank_worker:batch and bank_worker:transaction would simply pass the Pool Ref in to fun/1 to keep the interface the same without any harm.

I see more pros than cons for having a seperate connection process. Errors are handled nicer, the bank_worker may more easily keep its possible queue of requests, and the process dict remains clean.

**Comment by essen** [comment]
Heh I need to think a bit. First sounds better but I need to think about implementation details there.

**Comment by essen** [comment]
OK I see what you mean. I do not think adding a new process is going to make things better however, other than the "bad" use of the process dictionary I don't see any problem. Especially since adding a process means more code, more message passing, more chances to add bugs. I would do this instead though:

``` erlang
query(Ref, Query) ->
    case get('$bank_client_state') of
        undefined ->
            same_as_before;
        {Driver, State} ->
            State2 = bank_worker:do_query(Driver, Query, [], State)
            set('$bank_client_state', State2)
    end.
```

Of course `do_query/2` would also be used from inside the `bank_worker` code, and exported (but undocumented).

So all this would do for `bank_worker` is call an intermediate function (`bank:query/2`) instead of calling `do_query/4or5or6` directly. Stacktrace would be pretty obvious, queue is untouched, and we don't have to send 2 messages to do anything to the DB. At the cost of the process dictionary, but it considerably reduces the amount of code needed there.

**Comment by teburd** [comment]
Thinking more about it I think your right. The Fun gets passed to the bank worker after all, and it actually maximizes the SQL performance since its straight to the socket writting vs message passing.

I'll use the process dict for batch and transaction :+1:

**Comment by teburd** [comment]
Timeouts will be interesting :-)

**Comment by essen** [comment]
For timeouts I was wondering if we just want a timeout value or a list of options. I had another option in mind but forgot. Worse case it can easily be timeout() | [opt()].

**Comment by teburd** [comment]
How is bank_worker supposed to handle errors and reporting errors back to the caller?

I don't see anything about error handling/reporting

**Comment by teburd** [comment]
Just to add to this thought, what happens if there's an unhandled error in bank_worker to all the queued requests?

**Comment by essen** [comment]
If bank_worker crashes then all the requests fail. Not much you can do at that point, the socket is gone anyway, better discard everything than risk building up a huge queue.

**Comment by teburd** [comment]
It seems like bank could do better than that, maybe bank_server:get_worker(Ref) should be bank_server:get_unused_worker(Ref) or something like that.

**Comment by essen** [comment]
That's only beneficial for low traffic. The more queries you are going to do, the more statistics tell us that all workers are used equally.

On the other hand erlang:now() should probably be replaced by os:timestamp() there...

**Comment by ghost** [comment]
Making bank awesome sounds great to me! Starting with transaction support would be my first step too. :+1: 

Don't get me wrong, I think bank is already awesome!

**Comment by essen** [comment]
I renamed sql_query to query. Rest is up to you!

**Comment by essen** [comment]
Closing all tickets/PRs. Thanks!
