### ISSUE TITLE
Temporary Prepared Queries

### ISSUE THREAD

**Issue by teburd** [extend/bank#4]
Often times I'm just wanting to one off query not prepare a bajillion statements before going on.

Postgres supports this feature natively, and epgsql makes it available using equery.

MySQL can be made to act similiarly by killing the prepared statement after running

prepare/execute

I suggest following the epgsql method naming as

equery and squery as the abbreviated names are easy enough.

Otherwise matching like emysql does on execute/2 execute/3 would be nice instead of having what bank has now with sql_query and execute/3.

**Comment by essen** [comment]
Closing all tickets/PRs. Thanks!
