### ISSUE TITLE
auto reconnect and connection-bound database state

### ISSUE THREAD

**Issue by juhlig** [extend/bank#6]
Hello,

I haven't looked too deep into this project yet, but it sounds really good.

There is a problem with the automatic reconnection, though: data/state that is bound to a specific connection in the database server, like temporary tables, user-defined variables etc, will be lost when a disconnect occurs, and it will likely go unnoticed because of the automatic reconnect, at least when no temporary tables etc are used, but it may cause all kinds of unexpected havoc when there is.

We had an auto-reconnecting database driver in production for a while at our company. The developers tended to use it like it never disconnects (versus automatically reconnects), and thus we got into some trouble when temporary tables were involved.

How are you addressing this with bank?

**Comment by essen** [comment]
I haven't used it in a very long time so I don't think it was used like this (IIRC it was only used to query/insert on real tables, something very simple) but in general I would just have a callback (or a message, depending on the interface) after (re)connect to setup the connection before it can be used.

**Comment by juhlig** [comment]
Ok, thanks :)
